services:
  - type: web
    name: adult-search
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PW_HASH
        value: bea14985d52161d8bbfd5dee7235d31ed42eb037b11bfb38a2502519cdb996a1
